export * from './Header/Header.jsx';
export * from './Content/Content.jsx'
export * from './Banner/Banner.jsx';
export * from './Recipes/Recipes.jsx';
export * from './Categories/Categories.jsx';
export * from './Card/Card.jsx';
export * from './Detail/Detail.jsx';
export * from './Form/Form.jsx';
export * from './Areas/Area.jsx';
export * from './Ingredientes/Ingredients.jsx';
export * from './NotFound/NotFound.jsx'